name: who_logbook
description: "who logbook app Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Added for automatic App Icon generation
  flutter_launcher_icons: ^0.13.1

# Configuration for the App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF" # Change to your brand color
  adaptive_icon_foreground: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  # Registered the assets folder here
  assets:
    - assets/images/